<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <title><?= $title ?></title>
  <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
  <style type="text/css">
  body {
  }
  .content {
    font-size: large;
  }
  .pizhu {
    color: red;
    font-size: small;
    border: 1px solid red;
  }
  </style>
  <script type="text/javascript" src="js/jquery-2.1.0.min.js"></script>
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
  <script type="text/javascript">
  $(function () {
    $(document.body).on('mouseup', function (e) {
      console.log(window.getSelection());
    });
  });
  </script>
</head>
<body>
  <div class="content-wrap">
    <?php include $content_tpl ?>
  </div>
</body>
</html>
